name: "Release"
on: 
   push:
       tags:       
         - '*'

jobs:
  call-release:
    uses: CommonWealthRobotics/Bowler-Script-Release-CI/.github/workflows/reusable-release.yml@main
    with:
      filename: "Forky-archive"
      filelocation: "./ForkyLift.xml"   
  use-url-job:
    runs-on: ubuntu-latest
    needs: call-release
    steps:
      - run: echo "URL is:"${{ needs.call-release.outputs.outputURL }} 
